name: Build Docker Base Images

on:
  workflow_dispatch: # Allow manual trigger

permissions: {}

jobs:
  build-docker-base:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 20

      # TODO: Evaluate migrating to docker buildx bake to consolidate builds and improve cache sharing.
      - name: Build and push base2-build image
        run: >
          docker buildx build
          -f docker/debian-base.dockerfile
          --platform linux/amd64,linux/arm64,linux/arm/v7
          -t fognetx/uptime-kuma-distributed:base2-build
          -t fognetx/uptime-kuma-distributed:base2-slim
          --target base2-slim
          --cache-from type=gha
          --cache-to type=gha,mode=max
          .
          --push

      - name: Build and push base2-runtime image
        run: >
          docker buildx build
          -f docker/debian-base.dockerfile
          --platform linux/amd64,linux/arm64,linux/arm/v7
          -t fognetx/uptime-kuma-distributed:base2-runtime
          --target base2-slim-runtime
          --cache-from type=gha
          --cache-to type=gha,mode=max
          .
          --push

      - name: Build and push base2-poller image
        run: >
          docker buildx build
          -f docker/debian-base.dockerfile
          --platform linux/amd64,linux/arm64,linux/arm/v7
          -t fognetx/uptime-kuma-distributed:base2-poller
          --target base2-poller
          --cache-from type=gha
          --cache-to type=gha,mode=max
          .
          --push

      - name: Build and push base2 image
        run: >
          docker buildx build
          -f docker/debian-base.dockerfile
          --platform linux/amd64,linux/arm64,linux/arm/v7
          -t fognetx/uptime-kuma-distributed:base2
          --target base2
          --cache-from type=gha
          --cache-to type=gha,mode=max
          .
          --push
